version: '3.9'
services:

    # PHP service
    app:
        build:
          context: .
          dockerfile: ./docker/php/Dockerfile
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - nginx
            - db
        env_file:
            - .env
        networks:
            - app-network

    # MySQL database service
    db:
        build:
          context: .
          dockerfile: ./docker/mysql/Dockerfile
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker/mysql/sql/:/var/tmp/
        env_file:
            - .env
        networks:
            - app-network

    # Nginx service
    nginx:
        build:
          context: .
          dockerfile: ./docker/nginx/Dockerfile
        container_name: php-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge